[build]
  command = "yarn workspace site build"
  functions = "site/functions"
  publish = "site/public"

[dev] 
  framework = "#custom"
  command = "yarn develop" # Command to start your dev server
  targetPort = 8000 # port the app runs on
  # port = 53091 # port Netlify Dev runs on
  # functionsPort = 34568
  # publish = "site/public" # Folder with the static content for _redirect file
